CREATE DATABASE WhatsappProyectoFinal

USE WhatsappProyectoFinal

--DDL

CREATE TABLE Usuarios(
	UsuarioId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID() ,
	Nombre NVARCHAR(250) NOT NULL,
	Descripcion NVARCHAR(255),
	FotoPerfil TEXT NOT NULL,
	Telefono NVARCHAR(20) NOT NULL,
	FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()

);
GO
CREATE TABLE Grupos(
	GrupoId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre NVARCHAR(250) NOT NULL,
	FotoGrupal TEXT,
	Descripcion NVARCHAR(250),
);

GO
CREATE TABLE UsuariosGrupos(
	UsuarioGrupos INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UsuarioId UNIQUEIDENTIFIER NOT NULL ,
	GrupoId INT NOT NULL,
	CONSTRAINT FK_UsuariosGrupos FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId),
	CONSTRAINT FK_GruposUsuarios FOREIGN KEY (GrupoId) REFERENCES Grupos(GrupoId)
);
CREATE TABLE AdministradorGrupo(
	AdministadorId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID() ,
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	Permisos NVARCHAR(200) NOT NULL,
	Descripcion TEXT,
	CONSTRAINT FK_UsuarioAdministrador FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);

GO
CREATE TABLE Bloque(
	BloqueadorId UNIQUEIDENTIFIER NOT NULL,
	BLoqueadoId UNIQUEIDENTIFIER NOT NULL,
	FechaBloqueo DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	PRIMARY KEY (BloqueadorId,BLoqueadoId),
	CONSTRAINT FK_BloqueadorId FOREIGN KEY (BloqueadorId) REFERENCES Usuarios(UsuarioId),
    CONSTRAINT FK_BLoqueadoId FOREIGN KEY (BLoqueadoId) REFERENCES Usuarios(UsuarioId)

);

GO 

CREATE TABLE Estados(
	EstadosId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	URL TEXT NOT NULL,
	FechaPublicacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	FechaVencimiento DATETIME2  DEFAULT SYSUTCDATETIME()

	CONSTRAINT FK_UsuarioEstado FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);
GO

CREATE TABLE MensajeLeidos(
	MensajeLeidoID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	FechaLeido DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	CONSTRAINT FK_MensajeLeidoUsuario FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);
GO

CREATE TABLE Reacciones(
	ReaccionId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	Emoji TEXT NOT NULL,
	FechaReaccion  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	CONSTRAINT FK_UsuarioReaccion FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);
GO

CREATE TABLE ConversacionUsuario(
	ConversacionUsuarioId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	UsuarioId UNIQUEIDENTIFIER NOT NULL,
	MensajeSilenciado BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_UsuarioConversion FOREIGN KEY (UsuarioId) REFERENCES Usuarios(UsuarioId)
);
GO

CREATE TABLE Conversaciones(
	ConversacionId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ConversacionUsuarioId INT NOT NULL,
	Nombre NVARCHAR(250) NOT NULL,
	Descripcion NVARCHAR(250),
	FechaCreacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	CONSTRAINT FK_ConversacionUsuario FOREIGN KEY (ConversacionUsuarioId) REFERENCES ConversacionUsuario(ConversacionUsuarioId)

);
GO

CREATE TABLE EstadoMensaje(
	EstadoMensajeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NombreEstado NVARCHAR(50)
);
GO
CREATE TABLE Mensaje(
	MensajeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ConversacionId INT NOT NULL,
	EstadoMensajeId INT NOT NULL,
	ReaccionId INT NOT NULL,
	Contenido TEXT,
	TipoDocumento TEXT,
	FechaEnvio DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	MensajeEliminado BIT DEFAULT 1,
	RespuestaMensaje TEXT,

	CONSTRAINT FK_ConversaionMensajeId FOREIGN KEY (ConversacionId) REFERENCES Conversaciones(ConversacionId),
	CONSTRAINT FK_EstadoMensajeId FOREIGN KEY (EstadoMensajeId) REFERENCES EstadoMensaje(EstadoMensajeId)

)